import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import SideBarWrapper from "../components/SideBarWrapper";
import  { Toaster } from 'react-hot-toast';
import NextTopLoader from 'nextjs-toploader';

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = { title: "Next | Main", description: "Generated by create next app" };

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Toaster />
        <NextTopLoader />
        <Header />
        <div className="flex">
        <SideBarWrapper/>
        {children}
        </div>
      </body>
    </html>
  );
}
